### ISSUE TITLE
FileHash isn't database indexed

### ISSUE THREAD

**Issue by chillu** [open-sausages/custom-asset-store#2]
Can cause slow lookups on large database tables. That might be complex due to its nesting in `DBFile`.

**Comment by maxime-rainville** [comment]
I don't think `private static $indexes;` cares as long as there's a physical table with the name on the table. Just tested this locally and the index got created properly. 

```yml
SilverStripe\Assets\File:
  indexes:
    FileHash: true
```
